import type { Metadata } from "next";
import { Roboto, Alatsi } from 'next/font/google';
import './globals.css';

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

const alatsi = Alatsi({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-alatsi',
});

export const metadata: Metadata = {
  title: "ticketer",
  description: "Generated by create next appThis is a beginner-friendly yet practical Event Ticket Booking UI designed for developers to clone, explore, and build upon. The design focuses on a seamless, login-free ticket reservation flow, allowing users to book event tickets quickly and efficiently.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${alatsi.variable}`}>
        {children}
      </body>
    </html>
  );
}